config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "groups#index"
  resources :groups, only: [:index, :show, :new, :create]
  resources :expenses, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :group_expenses
  has_many :groups, through: :group_expenses

  validates :name, presence: true, length: { in: 3..20 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_expenses
  has_many :expenses, through: :group_expenses

  validates :name, presence: true, length: { in: 3..20 }
  validates :icon, presence: true

  def total_expenses
    expenses.sum(&:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expenses
  has_many :groups

  validates :name, presence: true, length: { in: 3..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @expense = Expense.new
    @groups = current_user.groups.order(:name)
    @group_id = params[:group_id]
    @back_group_path = {
      target: group_path(@group_id)
    }
  end

  def create
    @groups = current_user.groups
    params = expense_params
    @expense = Expense.new(name: params[:name], amount: params[:amount])
    @expense.author = current_user

    if @expense.save
      @group = Group.find(expense_params[:group_id])
      @expense.groups << @group
      redirect_to group_path(@group), notice: 'New expense added successfully'
    else
      flash[:alert] = 'Something went wrong, expense not created'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @groups = Group.includes(:expenses).where(user: current_user)
      @total_expenses = Expense.where(author: current_user).sum(&:amount)
      @categories = @groups.count
    else
      render '/splash/welcome'
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to root_path, notice: 'New category added successfully'
    else
      flash[:alert] = 'Something went wrong, category not created'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
      'active'
    else
      ''
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/expenses/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/expenses/new.html.erb
<div class="text-center mt-4">
  <%= link_to @back_group_path do %>
    <i class="fa-solid fa-circle-left fa-2x"></i>
  <% end %>
</div>

<div class="container" style="width: 40%;">
   <h2 class="text-center pt-4">Add a new Expense</h2>
   <%= form_with model: @expense, url: expenses_path, method: :post do |form| %>
   <%= render "shared/form_errors", form: form %>
   <div class="col-sm-10">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, :required => "required", placeholder: :name, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-sm-10">
      <%= form.label :amount, class: "form-label pt-2" %>
      <%= form.number_field :amount, :required => "required", autofocus: true, min: 0, step: 0.01, class: "form-control" %>
    </div>
    <div class="col-sm-10 mt-4">
      <%= form.select :group_id, @groups.collect { |group| [group.name, group.id] }, { :prompt => 'Select Category'}, class: "form-select", required: true %>
    </div>
    <div class="my-3">
        <%= form.submit "Add Expense", class: "btn btn-info" %>
    </div>
   <% end %>
</div>

app/views/groups/index.html.erb
<div class="container text-center mt-4">
  <% if current_user.groups.count > 2 %>
    <h2 class="my-4">Here are some of the expenses you are tracking</h2>
    <%= render "/shared/categories_carousel" %>  
  <% end%>
</div>
<div class="container" style="width: 50%;">
  <% if current_user.groups.any? %>
    <h3 class="my-4 text-center">You have tracked $<%= @total_expenses %> across <%= @categories %> categories</h3>
    <div class="row row-cols-1 row-cols-md-3">
      <% @groups.each do |group| %>
        <div class="col mb-4">
          <div class="card">
            <img src="<%= group.icon %>" class="rounded mx-auto d-block pt-2" alt="<%= group.name %>">
            <div class="card-body text-center">
              <h5 class="card-title"><%= group.name %></h5>
              <p class="card-text">Great job. You have tracked $<%= group.total_expenses %> of <%= group.name %></p>
              <p class="card-text mt-2"><small class="text-muted">Since <%= l group.created_at, format: :long %></small></p>
              <%= link_to "View", group_path(group), class: 'btn btn-info' %>
            </div>
          </div>
      </div>
      <% end %>
    </div>
  <% else %>
    <h2 class="my-4"> Welcome to the Rails Mint Expense Tracker</h2>
    <p> You don't have any category. Please click on the button below to add a category and start tracking your expenses </p>
  <% end %>
</div>
<div class="d-grid gap-2 col-3 mx-auto text-center">
  <%= link_to "Add Category", new_group_path, class: 'btn btn-info' %>
</div>

app/views/groups/new.html.erb
<%= render partial: "shared/back_button" %>
<div class="container category-form">
  <h2 class="text-center pt-4">Add a new Category</h2>
  <%= form_with model: @group, url: groups_path, method: :post do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="col-sm-10">
      <%= form.text_field :name, :required => "required", placeholder: :name, autofocus: true, class: "form-control" %>
    </div>
     <div class="col-sm-10">
        <em>(Enter a url link in the icon field)</em>
        <%= form.text_field :icon, :required => "required", placeholder: :icon, autofocus: true, class: "form-control" %>
    </div>
     <div class="my-3">
        <%= form.submit "Add Category", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<%= render partial: "shared/back_button" %>
<div class="container mt-4 d-flex flex-column align-items-center">
  <% if @group.expenses.none? %>
    <h1> You have not added any payments for the <%= @group.name %> Category</h1>
  <% else %> 
    <h1 class="text-center">These are the expenses of the <%= @group.name %> Category</h1>
    <h2 class="my-4 py-4 text-center">Great job. You have tracked $<%= @group.total_expenses %> of <%= @group.name %></h2>

    <% @group.expenses.order(created_at: :desc).each do |expense|%>
      <div class="card mb-3 expense-card">
        <div class="row g-0">
          <div class="col-md-4 d-flex flex-column align-items-center justify-content-center">
            <img src="<%= @group.icon %>" class="rounded mx-auto d-block" alt="...">
          </div>
          <div class="col-md-8 ">
            <div class="card-body d-flex justify-content-between align-items-center">
              <h5 class="card-title"><%= expense.name %></h5>
              <p class="card-text">$<%= expense.amount %></p>
            </div>
            <p class="card-text pt-4"><small class="text-muted"><%= l expense.created_at, format: :long %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= link_to "Add a new Expense", new_expense_path(group_id: @group[:id]), class: 'btn btn-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <div class="full-height">
      <% if user_signed_in? %>
        <%= render partial: "shared/hamburger_navbar" %>
      <% end %>
      <%= render partial: "shared/flash" %>
      <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_back_button.html.erb
<div class="text-center mt-4">
  <%= link_to root_path do %>
    <i class="fa-solid fa-circle-left fa-2x"></i>
  <% end %>
</div>

app/views/shared/_categories_carousel.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="<%= @groups.first.icon %>" class="rounded mx-auto d-block w-25" alt="<%= @groups.first.name %>">
      <div class="carousel-caption d-none d-md-block">
        <h5><%= @groups.first.name %></h5>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="<%= @groups.second.icon %>" class="rounded mx-auto d-block w-25" alt="<%= @groups.second.name %>">
      <div class="carousel-caption d-none d-md-block">
        <h5><%= @groups.second.name %></h5>
      </div>
    </div>
    <div class="carousel-item">
      <img src="<%= @groups.third.icon %>" class="rounded mx-auto d-block w-25" alt="<%= @groups.third.name %>">
      <div class="carousel-caption d-none d-md-block">
        <h5><%= @groups.third.name %></h5>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any?%>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_hamburger_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Rails Mint</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
         <li class="nav-item <%= active_class(groups_path) %>">
          <%= link_to "All Categories", groups_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="#"><%= current_user.email %> </a>
        </li>
        <li class="nav-item">
          <%= button_to( "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary') %>
        </li>
      <% else %>
        <li class="nav-item <%= active_class(new_user_session_path) %>">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= active_class(new_user_registration_path) %>">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_signed_out_footer.html.erb
<footer
  class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between pt-4 px-4 px-xl-5 bottom">
  <div class="text-white mb-1 mb-md-0">
    <p><small>&copy; 2022 Ben Kiarie. All rights reserved.</small></p>
  </div>
  <div>
    <a href="#" class="text-white me-4 footer-link">
      <i class="fa-brands fa-facebook"></i>
    </a>
    <a href="#" class="text-white me-4 footer-link">
      <i class="fab fa-twitter"></i>
    </a>
    <a href="#" class="text-white me-4 footer-link">
      <i class="fab fa-google"></i>
    </a>
    <a href="#" class="text-white footer-link">
      <i class="fab fa-linkedin-in"></i>
    </a>
  </div>
</footer>

app/views/shared/_signed_out_links.html.erb
 <div class="text-center mt-4">
    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-facebook-f"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-google"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-twitter"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-github"></i>
    </button>
</div>

app/views/splash/welcome.html.erb
<section class="animated-background">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div class="mb-md-5 mt-md-4 pb-5">
              <img src="https://res.cloudinary.com/optprime/image/upload/v1659361918/stash-it/4172b5aa4f784d9dac32fdd2ec8b7291_aknw39.png" class="rounded mx-auto d-block mb-5" alt="Logo">
              <p class="mb-3 fs-4">Welcome to Rails Mint</p>
              <p class="mb-5 fs-5 text-white-50">Take charge of your finances with Rails Mint online expense tracker</p>
              <div class="d-flex justify-content-around">
                <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light btn-lg px-5" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light btn-lg px-5" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>